#! /bin/sh

bspc monitor -d I II III


bspc config border_width        1
bspc config window_gap          18
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer       true
bspc config auto_alternate      false
bspc config auto_cancel         true
bspc config top_padding         16
bspc config normal_border_color "#181512"
bspc config focused_border_color "#A9A2A2"
bspc config presel_border_color "#AA759F"

bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.05

bspc rule -a Skype -d ^3 --floating
bspc config rule_command "$(which rule_command)"

bspwm_rules
panel &
