// Generated by CoffeeScript 1.3.3
(function() {
  var onExcludeUrl, onLoad;

  onLoad = function() {
    document.getElementById("optionsLink").setAttribute("href", chrome.extension.getURL("pages/options.html"));
    return chrome.tabs.getSelected(null, function(tab) {
      var domain;
      domain = tab.url.match(/[^\/]*\/\/[^\/]*\//) || tab.url;
      return document.getElementById("popupInput").value = domain + "*";
    });
  };

  onExcludeUrl = function(e) {
    var url;
    url = document.getElementById("popupInput").value;
    chrome.extension.getBackgroundPage().addExcludedUrl(url);
    return document.getElementById("excludeConfirm").setAttribute("style", "display: inline-block");
  };

  document.addEventListener("DOMContentLoaded", function() {
    document.getElementById("popupButton").addEventListener("click", onExcludeUrl, false);
    return onLoad();
  });

}).call(this);
