#!/bin/bash

tmux new-session -d -s foo 'exec weechat'
tmux split-window -v -p 60
tmux split-window -h -t 1
#tmux swap-pane -s 3 -t 1
tmux rename-window 'General'
tmux split-window -h -t 2

tmux new-window -n 'Music' 'exec ncmpcpp'
tmux split-window -v
tmux next-window
tmux new-window -d -n 'Ranger' 'exec ranger'
tmux attach-session -t foo
