#! /bin/sh

if ! rulc -l > /dev/null ; then
        (setsid ruld &)
        while ! rulc -l > /dev/null ; do
                sleep 0.1
        done
fi
rules=$(rulc -l)
if [ -z "$rules" ] ; then
        rulc -a 'class=="Firefox"' 'desktop=^2'
        rulc -a 'class=="Chromium"' 'desktop=^2'
        rulc -a 'class=="Eclipse"' 'desktop=^3 -l monocle'
        rulc -a 'class=="Skype"'   'desktop=^3 floating=on'
        rulc -a 'class=="calcurse"'   'desktop=^3 private=on'
	rulc -a 'class=="Wicd-client.py"'  'desktop=^1 floating=on'

fi
