#! /bin/sh
#
# Example panel for LemonBoy's bar

. panel_colors

# Colorscheme for mocho
#BLUE="#FF8AB3B5"
#RED="#FFCB6077"
#YELLOW="#FFF4BC87"
#ORANGE="#FFD28B71"
#MAGENTA="#FFA89BB9"
#TEAL="#FF7BBdA4"
#LIGHTGREY="#FFb8AfAD"
#DARKGREY="#FF7E705A"
#GREEN="#FF90A950"
#BG="#FF3B3228"
MIDDLE="#FF215666"

# Colorscheme for default-dark
BLUE="%{F#FF6A9FB5}"
RED="%{F#FFAC4142}"
YELLOW="%{F#FFFF4BF75}"
ORANGE="%{F#FFD28B71}"
MAGENTA="%{F#FFAA759F}"
TEAL="%{F#FF75B5AA}"
LIGHTGREY="%{F#FFB0B0B0}"
DARKGREY="%{F#FF505050}"
GREEN="%{F#FF99CC99}"
PURPLE="%{F#FF9547C9}"
BG="%{F#FF151515}"

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#?}"
			;;
		T*)
			# xtitle output
			# prevents titles from overshooting
			# my tag layout in the middle
			formatted=$(echo ${line#?} | cut -c1-85)
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}$formatted"
			;;
		E*)
			userInfo="${line#?}"
			;;
		M*)
			# M is for mail
			emailInfo="${line#?}"
			;;
		U*)
			updates="${line#?}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[OU]*)
						# focused occupied desktop
						wm_infos="$wm_infos  %{F$COLOR_FOCUSED_OCCUPIED_FG}%{U$COLOR_FOREGROUND}%{+u}%{U$ORANGE}"•"%{-u}"
						;;
					F*)
						#focused free desktop
						wm_infos="$wm_infos  %{F$COLOR_FREE_FG}%{U$COLOR_FOREGROUND}%{+u}○%{-u}"
						;;
					o*)
						# occupied desktop
						wm_infos="$wm_infos  %{F$COLOR_OCCUPIED_FG}•"
						;;
					f*)
						# free desktop
						wm_infos="$wm_infos  %{F$COLOR_FREE_FG}○"
						;;
					u*)
						# urgent desktop
						wm_infos="$wm_infos  %{F$COLOR_URGENT_FG}•"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}$userInfo $emailInfo $updates  $title %{c} %{F$BG}%{B$MIDDLE}⮀$wm_infos  %{F$BG}%{B$MIDDLE}⮂%{F$COLOR_TITLE_FG}%{B#FF3B3228}%{r} $sys_infos  "
done
