#! /bin/sh
#
# Example panel for LemonBoy's bar

while read -r line ; do
    case $line in
        S*)
            # clock output
            sys_infos="\\br\\f6${line#?}"
            ;;
        T*)
            # xtitle output
            title="\\br\\f7${line#?}"
            ;;
        W*)
            # bspwm internal state
            wm_infos=""
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    [OFU]*)
                        # active desktop
                        wm_infos="$wm_infos\\u3\\f8 • \\fr\\br\\ur"
                        ;;
                    o*)
                        # inactive but occupied desktop
                        wm_infos="$wm_infos\\f7 • \\fr"
                        ;;
                    f*)
                        # inactive desktop
                        wm_infos="$wm_infos\\f8 ○ \\fr"
                        ;;
                    u*)
                        # urgent desktop
                        wm_infos="$wm_infos \\f1•\\fr "
                        ;;
                    L*)
			layout=""
                        wm_infos="$wm_infos \\b4\\f0$layout\\br\\fr"
                        ;;
                esac
                shift
            done
            ;;
    esac
    printf "%s\n" "\\l ❭ $title \\c $wm_infos \\r $sys_infos "
done
