#! /bin/sh
#
# Example panel for LemonBoy's bar

. panel_colors

BLUE="#FF8AB3B5"
RED="#FFCB6077"
YELLOW="#FFF4BC87"
ORANGE="#FFD28B71"
MAGENTA="#FFA89BB9"
TEAL="#FF7BBdA4"
LIGHTGREY="#FFb8AfAD"
DARKGREY="#FF7E705A"
GREEN="#FF90A950"
BG="#FF3B3228"
MIDDLE="#FF215666"

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys_infos="%{F$COLOR_STATUS_FG}%{B$COLOR_STATUS_BG}${line#?}"
			;;
		T*)
			# xtitle output
			title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG}${line#?}"
			;;
		E*)
			userInfo="${line#?}"
			;;
		M*)
			# M is for mail
			emailInfo="${line#?}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					[OU]*)
						# focused occupied desktop
						wm_infos="$wm_infos  %{F$COLOR_FOCUSED_OCCUPIED_FG}%{U$COLOR_FOREGROUND}%{+u}%{U$ORANGE}"•"%{-u}"
						;;
					F*)
						#focused free desktop
						wm_infos="$wm_infos  %{F$COLOR_FREE_FG}%{U$COLOR_FOREGROUND}%{+u}○%{-u}"
						;;
					o*)
						# occupied desktop
						wm_infos="$wm_infos  %{F$COLOR_OCCUPIED_FG}•"
						;;
					f*)
						# free desktop
						wm_infos="$wm_infos  %{F$COLOR_FREE_FG}○"
						;;
					u*)
						# urgent desktop
						wm_infos="$wm_infos  %{F$COLOR_URGENT_FG}•"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "%{l}$userInfo $emailInfo  $title %{c} %{F$BG}%{B$MIDDLE}⮀$wm_infos  %{F$BG}%{B$MIDDLE}⮂%{F$COLOR_TITLE_FG}%{B#FF3B3228}%{r} $sys_infos  "
done
